[package]
name = "trout"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
once_cell = "1.19.0"
regex = "1.10.5"
syntect = "5.2.0"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.13"
yaml-rust = "0.4.5"
